### ISSUE TITLE
problem with making taxonomy file?

### ISSUE THREAD

**Issue by camillaln** [novichkov-lab/fama#7]
Hi,
I had to reinstall fama on a new server and I used the same 'recipe' that you sent me last year. However, I get an error:
Writing /gpfs/fs3c/aafc/aafc_shp/can0002/deep-metagenomes/fama/Gorzelak/nitrogen_v10/S00JY_0887_efpkg_functions.xlsx
Writing /gpfs/fs3c/aafc/aafc_shp/can0002/deep-metagenomes/fama/Gorzelak/nitrogen_v10/S00JY_0887_efpkg_functions_taxonomy.xlsx
Traceback (most recent call last):
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/fama/py/fama.py", line 58, in <module>
    main()
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/fama/py/fama.py", line 48, in main
    fastq_pe_pipeline(
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/fama/py/lib/pe_functional_pipeline.py", line 269, in fastq_pe_pipeline
    generate_sample_report(project, sample_id)
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/fama/py/lib/output/report.py", line 1089, in generate_sample_report
    make_func_tax_sample_xlsx(
  File "/gpfs/fs3c/aafc/aafc_shp/can0002/fama/py/lib/output/xlsx_util.py", line 205, in make_func_tax_sample_xlsx
    writer.save()
AttributeError: 'XlsxWriter' object has no attribute 'save'

Do you have any suggestions as to what is going wrong?
Thanks 
Camilla

**Comment by aekazakov** [comment]
This repository is no longer maintained. Please update the origin and pull the latest version:

`git remote set-url origin https://github.com/aekazakov/fama`
`git pull`
